myproject/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.contrib.auth import views as auth_views

from boards import views
from accounts import views as accounts_views

urlpatterns = [
    # path('', views.home, name='home'),
    # re_path(r'^homepage/$', views.home, name='home') to match 127.0.0.1:5000/homepage
    # url(r'^about/$', views.about, name='about'),
    # url(r'^about/company/$', views.about_company, name='about_company'),
    # url(r'^about/author/$', views.about_author, name='about_author'),
    # url(r'^about/author/vitor/$', views.about_vitor, name='about_vitor'),
    # url(r'^about/author/erica/$', views.about_erica, name='about_erica'),
    # url(r'^privacy/$', views.privacy_policy, name='privacy_policy'),
    # url(r'^(?P<username>[\w.@+-]+)/$',
    # views.user_profile, name='user_profile'),
    # re_path(r'^$', views.home, name='home'),
    re_path(r'^$', views.BoardListView.as_view(), name='home'),
    re_path(r'^signup/$', accounts_views.signup, name='signup'),
    re_path(r'^login/$',
            auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),

    re_path(r'^reset/$',
            auth_views.PasswordResetView.as_view(
                template_name='password_reset.html',
                email_template_name='password_reset_email.html',
                subject_template_name='password_reset_subject.txt'
            ),
            name='password_reset'),
    re_path(r'^reset/done/$',
            auth_views.PasswordResetDoneView.as_view(
                template_name='password_reset_done.html'),
            name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.PasswordResetConfirmView.as_view(
                template_name='password_reset_confirm.html'),
            name='password_reset_confirm'),
    re_path(r'^reset/complete/$',
            auth_views.PasswordResetCompleteView.as_view(
                template_name='password_reset_complete.html'),
            name='password_reset_complete'),

    re_path(r'^settings/account/$',
        accounts_views.UserUpdateView.as_view(), name='my_account'),
    re_path(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
            name='password_change'),
    re_path(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
            name='password_change_done'),

    re_path(r'^boards/(?P<pk>\d+)/$',
            views.TopicListView.as_view(), name='board_topics'),
    # re_path(r'^boards/(?P<pk>\d+)/$', views.board_topics, name='board_topics'),
    # path('boards/<int:pk>/', views.board_topics, name='board_topics'),
    re_path(r'^boards/(?P<pk>\d+)/new/$', views.new_topic, name='new_topic'),
    # re_path(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$',
            # views.topic_posts, name='topic_posts'),
    re_path(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$',
            views.PostListView.as_view(), name='topic_posts'),
    re_path(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/reply/$',
            views.reply_topic, name='reply_topic'),
    re_path(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/posts/(?P<post_pk>\d+)/edit/$',
            views.PostUpdateView.as_view(), name='edit_post'),
    path('admin/', admin.site.urls),
]

boards/models.py
from django.db import models
from django.utils.text import Truncator
# Create your models here.
from django.contrib.auth.models import User


class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_posts_count(self):
        return Post.objects.filter(topic__board=self).count()

    def get_last_post(self):
        return Post.objects.filter(topic__board=self).order_by('-created_at').first()


class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(
        Board, on_delete=models.CASCADE, related_name='topics')
    starter = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='topics')
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.subject

    def get_page_count(self):
        count = self.posts.count()
        pages = count / 20
        return math.ceil(pages)

    def has_many_pages(self, count=None):
        if count is None:
            count = self.get_page_count()
        return count > 6

    def get_page_range(self):
        count = self.get_page_count()
        if self.has_many_pages(count):
            return range(1, 5)
        return range(1, count + 1)

    def get_last_ten_posts(self):
        return self.posts.order_by('-created_at')[:10]


class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(
        Topic, on_delete=models.CASCADE, related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='posts')
    updated_by = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, related_name='+')

    def __str__(self):
        truncated_message = Truncator(self.message)
        return truncated_message.chars(30)

boards/forms.py
from django import forms
from .models import Topic, Post


class NewTopicForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea(
        attrs={'rows': 5, 'placeholder': 'What is on your mind?'}), max_length=4000, help_text='The max length of the text is 4000.')

    class Meta:
        model = Topic
        fields = ['subject', 'message']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message', ]

templates/includes/form.html
<!-- {% load widget_tweaks %} -->
<!-- {{ form.as_p }} -->
<!-- <div class="form-group">
        <label for="id_subject">Subject</label>
        <input type="text" class="form-control" id="id_subject" name="subject">
    </div>
    <div class="form-group">
        <label for="id_message">Message</label>
        <textarea class="form-control" id="id_message" name="message" rows="5"></textarea>
    </div> -->

{% load form_tags widget_tweaks %}

{% if form.non_field_errors %}
<div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
    <p{% if forloop.last %} class="mb-0" {% endif %}>{{ error }}</p>
        {% endfor %}
</div>
{% endif %}

{% for field in form %}
<div class="form-group">
    {{ field.label_tag }}
    {% render_field field class=field|input_class %}
    {% for error in field.errors %}
    <div class="invalid-feedback">
        {{ error }}
    </div>
    {% endfor %}
    {% if field.help_text %}
    <small class="form-text text-muted">
        {{ field.help_text|safe }}
    </small>
    {% endif %}
</div>
{% endfor %}

templates/includes/pagination.html
{% if is_paginated %}
<nav aria-label="Topics pagination" class="mb-4">
    <ul class="pagination">
        {% if page_obj.number > 1 %}
        <li class="page-item">
            <a class="page-link" href="?page=1">First</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">First</span>
        </li>
        {% endif %}

        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Previous</span>
        </li>
        {% endif %}

        {% for page_num in paginator.page_range %}
        {% if page_obj.number == page_num %}
        <li class="page-item active">
            <span class="page-link">
                {{ page_num }}
                <span class="sr-only">(current)</span>
            </span>
        </li>
        {% elif page_num > page_obj.number|add:'-3' and page_num < page_obj.number|add:'3' %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
        </li>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Next</span>
        </li>
        {% endif %}

        {% if page_obj.number != paginator.num_pages %}
        <li class="page-item">
            <a class="page-link" href="?page={{ paginator.num_pages }}">Last</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Last</span>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}